### PR TITLE
Added the functionality in show button to display all categories

### PR DESCRIPTION
**Pull request by Pratik2026**
https://github.com/PiyushKalyanpy/GyanaGuru/assets/128511266/9f93e5e9-b729-4fea-bcf4-8d0fd0094cda

I have added the functionality of a "Show More" button that, when clicked, displays all the categories. Additionally, I have included hover effects on the buttons.

For better understanding, please refer the attached video.

### CODE REVIEW

**Comment by parthpathakpp1** [comment]
@Pratik2026 need help . where can we connecy?

**Comment by Pratik2026** [comment]
Sure, we can connect on Discord. You can reach out to me using my username, Pratik_20#2097."

**Comment by Pratik2026** [comment]
@PiyushKalyanpy  I mistakenly forgot to ignore the package-lock.json and package.json files. One possible solution for this is to create a new branch associated with the existing PR  and then after making the necessary changes, overwrites the existing branch with the updated branch. Before proceeding further, I wanted to seek your approval to perform a force push and update the existing pull request with the corrected changes. If you prefer an alternative solution or have any specific instructions, please let me know, and I'll be happy to accommodate. I apologize for the inconvenience cause.

**Comment by parthpathakpp1** [comment]
> Sure, we can connect on Discord. You can reach out to me using my username, Pratik_20#2097." 
I have sent to the DM . Check it.

**Comment by PiyushKalyanpy** [comment]
@Pratik2026  if you want to push only a single file you can use ``` git add path/<file-name> ```

**Review by PiyushKalyanpy — CHANGES_REQUESTED** [review]
Please remove the hover blue color, and make it the same as it was earlier.

**Comment by Pratik2026** [comment]
I have removed the unwanted files and successfully implemented the requested changes. The hover blue color effect has been removed and the button now matches its original styling. Let me know if any further adjustments are needed.

**Comment by PiyushKalyanpy** [comment]
You have deleted the code for package.json and package.lock file, you don't have to do it, you have to make a new pr and you can  commit you code by ``` git add  Components/OurServices.tsx``` this command will only add single file not other files, then you can commit with you message and push the code.

**Pull request merged**
