### PR TITLE
[Feat] : Added Greeting Workflow

### PR DESCRIPTION
**Pull request by ujjawaltyagii**
## Description 📝

Closes : #297 

## Changes 💬

1. The workflow is triggered by multiple events, including forks, pushes to the main branch, opened issues, and opened pull requests.
2. The workflow utilizes the `EddieHubCommunity` action which is responsible for sending welcome messages to contributors.
3. The workflow incorporates dynamic content by using `GitHub context variables` i.e. It addresses contributors by their usernames.
4. It will greet every user with their `username` whenever they open any `Issue` or `PR`
## Additional Notes 📒

- I'm a gssoc contributor so please review my PR under gssoc labels !

### CODE REVIEW

**Comment by ujjawaltyagii** [comment]
@PiyushKalyanpy Done ! could you please review my PR under gssoc

**Review by lalitmee — CHANGES_REQUESTED** [review]
How do we know that it's working? Have you tested it somehow?

**Comment by lalitmee** [comment]
> @lalitmee I don't think we can test it without merging it as it's a github workflow. Although I have worked on github workflow and action previously !!

I think we can test, what you can do is create a dummy repository just to test this action and then copy this workflow into that dummy repository. And then take action on which this workflow will trigger. 

The thing is that it is best to test before merging anything rather than coming back to it again and again.

Let me know if you need any help.

**Comment by PiyushKalyanpy** [comment]
What are the updates @ujjawaltyagii ??

**Comment by ujjawaltyagii** [comment]
working on it to test things out ! I have exams going on right now so will update soon with the testing results/changes in PR

**Comment by lalitmee** [comment]
> @PiyushKalyanpy working on it to test things out ! I have exams going on right now but will update soon with the testing results/changes in PR

@ujjawaltyagii, take your time. But try to complete it.

**Comment by PiyushKalyanpy** [comment]
We are closing this pull request as the changes we requested were not implemented. Please reopen the PR once you are done with the requested changes.

**Pull request closed without merging**
