### PR TITLE
This commit adds the Name ,Email and Message text box for the user to…

### PR DESCRIPTION
**Pull request by parthksingh1**
… contact the owner and to tell them their descriptive information. It also includes the form submission that allows the owner to know who access the contact section.

I Have added the the Name, Email and Message text box in the Contact us section to allow the user to message the owner to let the owner know the problems or to get more information , I have also included the Form submission which will let know the owner about who filled the form. 

Screenshot (7)

### CODE REVIEW

**Comment by parthpathakpp1** [comment]
> … contact the owner and to tell them their descriptive information. It also includes the form submission that allows the owner to know who access the contact section.
> 
> I Have added the the Name, Email and Message text box in the Contact us section to allow the user to message the owner to let the owner know the problems or to get more information , I have also included the Form submission which will let know the owner about who filled the form.
> 
> Screenshot (7)

@parthksingh1 i have some questions regarding this project . I am also contributing in the project . Where can I ask my question to you?

**Review by PiyushKalyanpy — CHANGES_REQUESTED** [review]
I suggest you to make different PR's for different file changes.......
You have done changes in package-lock.json file and package.json file
So can you please make a new PR with only changes in  LandingContact.tsx

Thank you.....

**Comment by PiyushKalyanpy** [comment]
@parthksingh1 can you please help on this issue - #28

**Comment by parthksingh1** [comment]
> 

Sure, I will try

**Pull request merged**
