### PR TITLE
Fixed : Issue#29

### PR DESCRIPTION
**Pull request by parthpathakpp1**
I fixeD the issue #29 which was **Improving Footer Section** . I improved the footer section . 
Before-:
gyanagurubefore

**After-:**
gyanaguruimprovedfooter

### CODE REVIEW

**Review by PiyushKalyanpy — CHANGES_REQUESTED** [review]
Please make a new pr which contains the required files only. ( do not push firebase.js and package files

**Comment by parthpathakpp1** [comment]
> Please make a new pr which contains the required files only. ( do not push firebase.js and package files

okay

**Comment by parthpathakpp1** [comment]
> Please make a new pr which contains the required files only. ( do not push firebase.js and package files

@PiyushKalyanpy **As I added social media icons . so I had to install react-icons dependency in package.json file . So whAs I added social media icons . so I had to install react-icons dependency in package.json file . So what should I do?**
at should I do?

**Comment by parthpathakpp1** [comment]
> > Please make a new pr which contains the required files only. ( do not push firebase.js and package files
> 
> okay



> Please make a new pr which contains the required files only. ( do not push firebase.js and package files

This is the new pull request  . I only added required files. 
**LINK-: https://github.com/PiyushKalyanpy/GyanaGuru/pull/101**

**Pull request closed without merging**
