### PR TITLE
Dark Mode with required changes  #41 Issue  GsSoC'23

### PR DESCRIPTION
**Pull request by Nikhil1017**
@PiyushKalyanpy The following changes have been made
1) I have fixed all the issues you pointed out.
2) I have put the Get Started Button and Dark mode button in a div with tailwind spacing of 4 as you said.
3) I have changed the icons to Google Icons as you suggested.
4) I have also added Dark Mode for the new Faq page.
5) I have changed all Dark Mode colors to zinc as you suggested.
This is in reference to PR #82 

Here are some screenshots

image
image

### CODE REVIEW

**Comment by Nikhil1017** [comment]
@PiyushKalyanpy please reply

**Comment by PiyushKalyanpy** [comment]
It's really amazing @Nikhil1017 🎉, Thank you for your valuable contribution 🙌. We will look forward to more contributions from you 😇

**Comment by Nikhil1017** [comment]
Thank you😃. i look forward to contributing more to this codebase

**Comment by PiyushKalyanpy** [comment]
Hello @Nikhil1017 , would you like to add dark mode to dashboard and other pages ??

**Comment by Nikhil1017** [comment]
@PiyushKalyanpy Sure, Do you have any specific instructions or Color preferences like last time? Otherwise I will just stick with the same zinc color theme used last time.

**Pull request merged**
