### PR TITLE
Enforce npm version

### PR DESCRIPTION
**Pull request by Nikhil1017**
The following changes have been done
1) .npmrc file added
2) npm version has been set in package.json
as per Issue #413

### CODE REVIEW

**Comment by Nikhil1017** [comment]
@PiyushKalyanpy sorry I was a bit frustrated, I have created a new pull request as you said with only .npmrc and package.json file. eslint was already merged, so not included.

**Review by PiyushKalyanpy — APPROVED** [review]

**Comment by PiyushKalyanpy** [comment]
Please add the issue number in the description.

**Comment by PiyushKalyanpy** [comment]
🎉 Thank you for your valuable contribution @Nikhil1017

**Comment by Nikhil1017** [comment]
Thanks

**Pull request merged**
