### PR TITLE
Update CODE OF CONDUCT.md

### PR DESCRIPTION
**Pull request by akash19coder**
Fixes/ Closes : Issue #196

### CODE REVIEW

**Comment by akash19coder** [comment]
We actually need a place where the code of conduct violation can be reported.
enforcementAddress

**Comment by PiyushKalyanpy** [comment]
Please add the issue number in the description.

**Review by lalitmee — COMMENTED** [review]
Hey @akash19coder, can you please try putting the content of this file in Grammarly and then try fixing some obvious things which can be fixed? I tried and found so many things which can be fixed in one click.

**Comment by akash19coder** [comment]
> Hey @akash19coder, can you please try putting the content of this file in Grammarly and then try fixing some obvious things which can be fixed? I tried and found so many things which can be fixed in one click.

I have actually done it. I have corrected mistakes using Grammarly

**Comment by lalitmee** [comment]
@akash19coder, there are so many files coming in your PR. Please fix your PR only to have those changes which you want to push.

**Review by vedprakashnautiyal — CHANGES_REQUESTED** [review]
It would be better if you could create separate PR's for different changes

**Pull request closed without merging**
