### PR TITLE
workflows for preview and production deployment with authorization in…

### LINKED ISSUE #113: [Feature] Auto authorisation in vercel using Github actions
Create workflows for preview and production environment

### PR DESCRIPTION
**Pull request by Tushar98644**
Fixes #113 

@PiyushKalyanpy kindly review

### CODE REVIEW

**Comment by PiyushKalyanpy** [comment]
Thankyou for your contribution @Tushar98644 🎉

**Comment by PiyushKalyanpy** [comment]
@Tushar98644  but it is not working, the PR's are not automatically authorised !

**Comment by Tushar98644** [comment]
> @Tushar98644 but it is not working, the PR's are not automatically authorised !

did you add the vercel id and project id to repo secrets?

**Comment by PiyushKalyanpy** [comment]
yes  but it is not working

**Comment by Tushar98644** [comment]
> yes but it is not working

I will push a update soon..

**Comment by PiyushKalyanpy** [comment]
It is working fine now, if there is any problem I will let you know.

**Pull request merged**
