### PR TITLE
feat: add github action to lock new issues

### PR DESCRIPTION
**Pull request by harmeetsingh11**
## Description 📝

Fixes/Closes: #469 

Added github action workflow to lock new issues.

## Files added 💬

- `.github/workflows/lock.yml`

### Type of change
What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.

Please review this PR
Thanks.

### CODE REVIEW

**Comment by harmeetsingh11** [comment]
@PiyushKalyanpy please review this PR 
Thanks

**Review by lalitmee — APPROVED** [review]

**Comment by harmeetsingh11** [comment]
@PiyushKalyanpy please add gssoc23 label and label to the PR, otherwise my PR won't count.

**Comment by PiyushKalyanpy** [comment]
> @PiyushKalyanpy please add gssoc23 label and label to the PR, otherwise my PR won't count.

Sorry for the inconvenience @harmeetsingh11 , I have updated the labels. We look forward to receiving more contributions from you.

**Comment by harmeetsingh11** [comment]
Thanks 
Glad to be a contributor of this project!
Will try to contribute as much as possible.😊

**Comment by PiyushKalyanpy** [comment]
Hey @harmeetsingh11 locking issues are not working please check, and resolve the problem.

**Comment by harmeetsingh11** [comment]
@PiyushKalyanpy You need to enable the permissions to run any workflow. Here's how to do it:

### To run this workflow you need to enable the following permission:

1. **Go to your project repository settings**
2. **On left pane > Actions > General**

image

3. **Scroll down and Go to Workflow permissions > select "Read and write permissions"**

image

4. **Click save and its done.**

**Comment by PiyushKalyanpy** [comment]
Why issues are not unlocked when label is added ??

**Pull request merged**
