### PR TITLE
Fixed : issue #124 Add relevant images

### PR DESCRIPTION
**Pull request by charu210703**

### CODE REVIEW

**Comment by charu210703** [comment]
@PiyushKalyanpy kindly merge this PR

**Comment by lalitmee** [comment]
@charu210703, please resolve the conflicts first and please add some description in the PR about your changes. So that it is easier for us to get the context of the PR and we can review it asap.

**Comment by charu210703** [comment]
Sorry, I will fix this by tuesday EOD.

**Comment by PiyushKalyanpy** [comment]
Dear @charu210703  👋

Thank you for taking the time to submit a pull request to our project. We appreciate your contribution and the effort you've put into it.

🔍 After careful consideration and review by our team, we have decided not to accept this particular pull request at this time. We have evaluated the changes and determined that they are not aligned with our project's goals, **requirements**, or coding guidelines.

Please understand that this decision does not reflect the quality of your work or your skills as a contributor. We value your efforts and encourage you to continue contributing to open-source projects.

We encourage you to keep an eye on our project's repository for future opportunities where your contributions may align more closely with our needs. Additionally, feel free to contribute to other open-source projects that match your interests and expertise.

Thank you once again for your interest in our project and for your contribution. We appreciate your understanding.

**Pull request closed without merging**
