### PR TITLE
send email through contact form using firebase realtime database [GSSOC'23] 

### PR DESCRIPTION
**Pull request by shivaniyuvrajyadav**
## Description 📝

Fixes/Closes: #287 
store user data from contact form

## Changes 💬
   - remove formsubmit.co
    - added firebase realtime database
    - changes in Landingcontact.tsx file

### CODE REVIEW

**Comment by PiyushKalyanpy** [comment]
Please c areate new pr.

**Comment by shivaniyuvrajyadav** [comment]
> Please c areate new pr.

I have close previous pr. This is new pr

**Comment by PiyushKalyanpy** [comment]
Why are you deleting package files??? Read the contribution guide to push only the required files.
image

**Comment by shivaniyuvrajyadav** [comment]
> Why are you deleting package files??? Read the contribution guide to push only the required files. image



> Why are you deleting package files??? Read the contribution guide to push only the required files. image

In my previous pr, you were saying to delete the package. lock.json from pr

**Comment by PiyushKalyanpy** [comment]
You don't have to push the package file in PR. You can see how many changes you have made! This is not what a PR looks like.  You have to only push the files which you have changes , so don;t push package file.

image

**Comment by shivaniyuvrajyadav** [comment]
> You don't have to push the package file in PR. You can see how many changes you have made! This is not what a PR looks like. You have to only push the files which you have changes , so don;t push package file.
> 
> image

I'm closing this pr and will create a new pr which contains only the files that I had made the changes

**Pull request closed without merging**
