### PR TITLE
#68PositionFixed

### PR DESCRIPTION
**Pull request by piyushkhurana2019**
#68 solved i.e. Position of the main text got fixed.
Screenshot 2023-05-21 at 2 10 47 PM

### CODE REVIEW

**Comment by piyushkhurana2019** [comment]
@PiyushKalyanpy please provide vercel authorization and approve my pull request

**Comment by PiyushKalyanpy** [comment]
Please make it flex-row as it was earlier, what you can change is : add media query, which will use flex-col only when size is not large.

**Comment by piyushkhurana2019** [comment]
@PiyushKalyanpy , sir i am not able to set up this repo in my local as it requires firebase api, i am working on mac and i didn't found any useful resources about how to set up and run this repo in my local. will you plz guide me, i will be a great opportunity for me to learn from you, ThankYou

**Comment by PiyushKalyanpy** [comment]
@piyushkhurana2019 you can try it now, i have removed the firebase files.

**Comment by piyushkhurana2019** [comment]
i have done it sir, kindly have a look at PR #145 and please merge it

**Pull request closed without merging**
