### PR TITLE
made changes 

### PR DESCRIPTION
**Pull request by bhavyanarnoli**
## Description 📝

Fixes/Closes: <issue/link> #329
https://github.com/PiyushKalyanpy/GyanaGuru/issues/329
## Changes 💬

- High-level overview of the changes introduced.
- Step-by-step breakdown of the implementation, if applicable.

## Screenshots (if applicable)
add tailwind in package.json and changed why choose us 
Include relevant screenshots or GIFs demonstrating the changes, especially for UI-related updates.

## Additional Notes 📒

Include any additional information or context that might be helpful for the reviewers. 
***Also if you are fixing the already made PR and the reviewer demands some change in it then, in each PR you have to mention the issue you have fixed in it.***
image
image

### CODE REVIEW

**Comment by PiyushKalyanpy** [comment]
please optimize it for light theme.

**Comment by bhavyanarnoli** [comment]
image

**Comment by bhavyanarnoli** [comment]
image

**Comment by bhavyanarnoli** [comment]
@PiyushKalyanpy pls see

**Comment by PiyushKalyanpy** [comment]
for  light theme use background seafoam (defined in the tailwind config file) not dark.

**Comment by bhavyanarnoli** [comment]
@PiyushKalyanpy i made the changes pls let me know

**Comment by PiyushKalyanpy** [comment]
This pr is not a valid pr, please read the contribution guide and the required filed only. Please create a new pr.

**Comment by bhavyanarnoli** [comment]
i didnt get the exact issue?

**Comment by bhavyanarnoli** [comment]
@PiyushKalyanpy
can you tell what it exactly means

**Pull request closed without merging**
