### PR TITLE
💡 FEAT: ADD ARIA-LABELS FOR SOCIAL MEDIA ANCHOR ELEMENTS

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Description 📝

- The goal of this PR is to add `aria-label` attributes for the social media anchor elements on `footer`.
- This helps to improve the accessibility of our Application and makes it to be used by any type of disabled peoples who relay on screen readers
- This PR Fixes/Closes: #224 

## Checklist ✅

- [x] Reviewed the code changes thoroughly.
- [x] Tested the changes locally and ensured they work as expected.
- [x] Updated relevant documentation.
- [x] Added appropriate test cases, if applicable.
- [x] Considered potential security or performance implications.
- [x] Code adheres to the project's style guidelines.
- [x] Addressed all reviewer comments and concerns, if any.

## Reviewers:
- @PiyushKalyanpy

### CODE REVIEW

**Comment by lalitmee** [comment]
@0xabdulkhalid, please don't put a title of the PR like this. Please use all small case letters. Can you please update the title?

**Review by lalitmee — CHANGES_REQUESTED** [review]
@0xabdulkhalid, please update the `href` with the correct URLs for the `anchor` tag which doesn't have valid URLs, and also add `target="_blank"` for every `anchor` tag.

@PiyushKalyanpy, please provide the correct URLs for all the social icons.

**Comment by 0xabdulkhalid** [comment]
Hello @lalitmee, as per your request i have fixed those broken crawlers.

But we still want  Instagram & Twitter Profile URL of @PiyushKalyanpy

**Comment by 0xabdulkhalid** [comment]
Hello @lalitmee,

- Proper links for @PiyushKalyanpy has not been found for Twitter, Facebook & Instagram.
- So i update the link for them as `#` which will act as a local crawler (Dummy link)
- Now the conflicts with those links are resolved, kindly consider to merge this PR.

Regards!

**Review by lalitmee — APPROVED** [review]
LGTM

**Pull request merged**
