### PR TITLE
Feature/add sidebar menu dashboard

### PR DESCRIPTION
**Pull request by kirtiraj22**
This PR resolves issue number #48 
### **Description :** 
This pull request adds a new feature to the admin dashboard: a sidebar menu. 

### Changes Made:

- [x] Implemented a sidebar menu with 6 links: Dashboard, Courses, Settings, Profile, Help and Support, and Logout.
- [x] Updated SVG images for all sidebar menu links, except for Profile and Help and Support.

### Things to be done : 
- Update the router.push() links in the sidebar menu to ensure proper navigation.
- Create separate components for each sidebar option (Dashboard, Courses, Settings, Profile, Help and Support, and Logout).
- Update the SVG icons for the Profile and Help and Support links to differentiate them from the Settings icon.

**NOTE :** We can raise 3 separate issue for the above 3 things which are quite basic (the contributor just need to add 2 svgs , need to update the link in router.push and break the component into different components). This will allow beginners to contribute to the repo.

### **Screenshots :** 

**Before :** 

Screenshot (142)

**After :** 

Screenshot (141)

hey, @PiyushKalyanpy Kindly review and merge this pull request.

### CODE REVIEW

**Review by PiyushKalyanpy — CHANGES_REQUESTED** [review]
Please make a new pr, which should only include the required files and remove unnecessary files. ( it should only include the file that is affecting the dashboard, remove the file where you have done changes for Firebase and other changes)

**Comment by PiyushKalyanpy** [comment]
Please do not use the hardcoded values, you should only use the pre-defined tailwind classes.

**Comment by kirtiraj22** [comment]
Hey @PiyushKalyanpy, I apologize for using hardcoded Tailwind CSS values. Moving forward, I will ensure that I utilize the appropriate Tailwind classes.

**Comment by PiyushKalyanpy** [comment]
Hello @kirtiraj22 could you please make a new PR for the left sidebar and with issue number #48

**Pull request merged**
